apiVersion: v1
kind: Service
metadata:
   name: "vistra-{{deployment_env_short}}-weather-api"
   namespace: "{{eks_namespace}}"
   annotations:
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "{{db_security_group}}"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "business_unit={{tag_BusinessUnit | lower}},application_code={{tag_ApplicationCode | lower}},application_name={{tag_ApplicationName | lower}},environment={{tag_Environment | lower}},owner={{tag_Owner | lower}},data_classification={{tag_DataClassification | lower}},pci={{tag_PCI | lower}},sox={{tag_SOX | lower}},nerc-cip={{tag_NERCCIP | lower}},archive_date={{tag_ArchiveDate | lower}},monitoring={{tag_Monitoring | lower}},application_criticality={{tag_ApplicationCriticality | lower}},project={{tag_Project | lower}},contact={{tag_Contact | lower}},cmdb={{tag_CMDB | lower}}"
    {{eks_elb_annotation}}
spec:
  selector:
    app: "vistra-{{deployment_env_short}}-weather-api"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: vistra-weather-api-nodeport
  namespace: "{{eks_namespace}}"
spec:
  selector:
    app: "vistra-{{deployment_env_short}}-weather-api"
  ports:
    - port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-guardian-grrf
  namespace: weather-services
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/rewrite-target: /

    kubernetes.io/ingress.class: alb
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/scheme: internal
    {{eks_alb_annotation}}
    alb.ingress.kubernetes.io/tags: "business_unit={{tag_BusinessUnit | lower}},application_code={{tag_ApplicationCode | lower}},application_name={{tag_ApplicationName | lower}},environment={{tag_Environment | lower}},owner={{tag_Owner | lower}},data_classification={{tag_DataClassification | lower}},pci={{tag_PCI | lower}},sox={{tag_SOX | lower}},nerc-cip={{tag_NERCCIP | lower}},archive_date={{tag_ArchiveDate | lower}},monitoring={{tag_Monitoring | lower}},application_criticality={{tag_ApplicationCriticality | lower}},project={{tag_Project | lower}},contact={{tag_Contact | lower}},cmdb={{tag_CMDB | lower}}"
    alb.ingress.kubernetes.io/security-groups: "{{db_security_group}}"
spec:
  # tls:
  # - hosts:
  #   - applebanana.local
  #   secretName: tls-secret
  rules:
  - host: cts-weather-services.com
    http:
      paths:
        - path: /*
          backend:
            serviceName: vistra-weather-api-nodeport
            servicePort: 80



