---
#####################################################################################################
#                                                                                                   #
# Usage:                                                                                            #
#                                                                                                   #
# ansible-playbook main.yml -e "deployment_env=aia"                                                #
# ansible-playbook main.yml -e "deployment_env=non-prod"                                            #
# ansible-playbook main.yml -e "deployment_env=prod"                                                #
#                                                                                                   #
# other options:                                                                                    #
#                                                                                                   #
# ansible-playbook main.yml -e "deployment_env=non-prod nocyberark=1 nodataload=1"                  #
# ansible-playbook main.yml -e "deployment_env=prod nocyberark=1 nodataload=1"                      #
# ansible-playbook main.yml -e "deployment_env=aia nocyberark=1 nodataload=1"                      #
# ansible-playbook main.yml -e "deployment_env=aia nocyberark=1"                                   #
#                                                                                                   #
#####################################################################################################

- hosts: localhost
  remote_user: root

  vars:
    - deployment_env: aia      # must be overwritten with an inline variable. eg: ... -e "deployment_env=non-prod"

  tasks:
    - include_vars: "./environments/vars_common.yaml"                    # common vars same in all environments
    - include_vars: "./environments/{{ deployment_env }}/vars-app.yml"   # variables specific to guardian grrf

    # - block:
#######################################################################################################
    - name: execute guardian grrf specific roles
      include_role:
        name: "{{role_item}}"
      loop:
        - ws-00-vpc-create            # executed only if execute_vpc_create is defined
        - ws-00-vpc-sg                # executed only if execute_vpc_sg is defined
        - ws-01-eks-create            # executed only if execute_eks_create is defined
        # - ws-02-postgres-create       # executed only if execute_postgres_create is defined
        # - ws-04-repository-create
        # - ws-05-container
        - ws-07-eks-prepare
        # - ws-07-eks-setup
      loop_control:
        loop_var: role_item
#######################################################################################################
      # always:
#######################################################################################################

#######################################################################################################