---
#####################################################################################################
#                                                                                                   #
# Usage:                                                                                            #
#                                                                                                   #
# ansible-playbook retract.yaml -e "deployment_env=aia"                                                #
# ansible-playbook retract.yaml -e "deployment_env=non-prod"                                            #
# ansible-playbook retract.yaml -e "deployment_env=prod"                                                #
#                                                                                                   #
# ansible-playbook retract.yaml -e "deployment_env=aia nocyberark=1"                                   #
# ansible-playbook retract.yaml -e "deployment_env=non-prod nocyberark=1"                               #
# ansible-playbook retract.yaml -e "deployment_env=prod nocyberark=1"                                   #
#                                                                                                   #
#####################################################################################################

- hosts: localhost
  remote_user: root

  vars:
    - deployment_env: aia      # must be overwritten with an inline variable. eg: ... -e "deployment_env=non-prod"

  tasks:
    - include_vars: "./environments/vars_common.yaml"                            # common vars same in all environments
    - include_vars: "./environments/{{ deployment_env }}/vars-app.yml"        # variables specific to guardian grrf

    # - block:
#######################################################################################################
    - name: execute guardian grrf specific roles
      include_role:
        name: "{{role_item}}"
      loop:
        - ws-99-retract
      loop_control:
        loop_var: role_item
#######################################################################################################
      # always:
#######################################################################################################

#######################################################################################################